name: Create Docker Image for Testnets

on:
  push:
    branches:
      - "main"
      - "ghost"
jobs:
  docker:
    strategy:
      matrix:
        network: [ghostnet]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%dT%H-%M-%S)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        id: docker_build_tzportal
        uses: docker/build-push-action@v2
        with:
          file: ./portal/Dockerfile.${{ matrix.network }}
          context: ./portal/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/tzportal:latest-${{ matrix.network }}

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/ghost' }}
        id: docker_build_tzportal_ghostnet
        uses: docker/build-push-action@v2
        with:
          file: ./portal/Dockerfile.${{ matrix.network }}
          context: ./portal/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: true
          tags: |
            ghcr.io/marigold-dev/tzportal:stable-${{ matrix.network }}
            ghcr.io/marigold-dev/tzportal:${{ steps.vars.outputs.date }}-${{ github.sha }}-${{ matrix.network }}
